"""Exploratory data analysis on the unified panel.

Reads ``data/processed/analysis_panel.csv`` and produces the EDA artifacts:
figures in ``outputs/figures/``, a printed report, and a written findings note
``reports/eda_findings.md``. The numbers in the note are computed here, not
typed by hand, so the narrative always matches the data it describes.

No modeling happens here — overdispersion and correlations are only measured, to
justify the negative-binomial choice and the climate lag explored separately.
"""

import pandas as pd

from dengue_climate.config import PROJECT_ROOT, get_path
from dengue_climate.viz.plots import (
    BAND_ORDER,
    MONTHS,
    plot_cases_climate_overlay,
    plot_cases_concentration,
    plot_cases_distribution,
    plot_correlation_heatmap,
    plot_seasonality_by_band,
)

CLIMATE_VARS = ["precip", "temp_mean", "temp_max", "temp_min", "humidity"]


def load_panel() -> pd.DataFrame:
    """Read the analysis panel with its elevation bands in low→high order."""
    panel = pd.read_csv(get_path("analysis_panel"))
    panel["elevation_band"] = pd.Categorical(
        panel["elevation_band"], categories=BAND_ORDER, ordered=True
    )
    return panel


def overdispersion(panel: pd.DataFrame) -> pd.DataFrame:
    """Mean, variance and their ratio for cases, overall and per band.

    A variance far above the mean (ratio ≫ 1) is overdispersion: the signal that
    Poisson is too tight and a negative-binomial is warranted.
    """
    def stats(s: pd.Series) -> dict[str, float]:
        return {"mean": s.mean(), "variance": s.var(),
                "var_mean_ratio": s.var() / s.mean() if s.mean() else float("nan"),
                "pct_zero": 100 * (s == 0).mean()}

    rows = {"All": stats(panel["cases"])}
    for band in BAND_ORDER:
        sub = panel.loc[panel["elevation_band"] == band, "cases"]
        if len(sub):
            rows[band] = stats(sub)
    return pd.DataFrame(rows).T.round(1)


def correlations(panel: pd.DataFrame) -> tuple[pd.Series, pd.DataFrame]:
    """Cases-vs-climate correlation overall and split by elevation band."""
    overall = panel[["cases", *CLIMATE_VARS]].corr()["cases"].drop("cases").round(2)
    per_band = (
        panel.groupby("elevation_band", observed=True)
        .apply(lambda g: g[["cases", *CLIMATE_VARS]].corr()["cases"].drop("cases"),
               include_groups=False)
        .round(2)
    )
    return overall, per_band


def concentration(panel: pd.DataFrame) -> tuple[pd.DataFrame, pd.Series]:
    """Total/share of cases per band and the ten heaviest districts."""
    by_band = panel.groupby("elevation_band", observed=True)["cases"].sum()
    band_tbl = pd.DataFrame(
        {"total_cases": by_band, "share_pct": (100 * by_band / by_band.sum()).round(1)}
    )
    top = panel.groupby("district")["cases"].sum().nlargest(10)
    return band_tbl, top


def peak_months(panel: pd.DataFrame) -> dict[str, str]:
    """The calendar month of peak mean cases, overall and per band."""
    def peak(df: pd.DataFrame) -> str:
        m = df.groupby("month")["cases"].mean().idxmax()
        return MONTHS[m - 1]

    out = {"All": peak(panel)}
    for band in BAND_ORDER:
        sub = panel[panel["elevation_band"] == band]
        if len(sub):
            out[band] = peak(sub)
    return out


def _md_table(df: pd.DataFrame, index_name: str) -> str:
    """Render a DataFrame as a GitHub-flavoured markdown table (no deps)."""
    cols = [index_name, *map(str, df.columns)]
    lines = ["| " + " | ".join(cols) + " |",
             "| " + " | ".join(["---"] * len(cols)) + " |"]
    for idx, row in df.iterrows():
        cells = [str(idx)] + [f"{v:g}" if isinstance(v, float) else str(v) for v in row]
        lines.append("| " + " | ".join(cells) + " |")
    return "\n".join(lines)


def write_findings(panel, disp, overall_corr, per_band_corr, band_tbl, top, peaks):
    """Write reports/eda_findings.md from the computed numbers."""
    ratio = disp.loc["All", "var_mean_ratio"]
    zero = disp.loc["All", "pct_zero"]
    strongest = overall_corr.abs().idxmax()

    md = f"""# EDA findings — dengue × climate × elevation

*Generated by `analysis/eda.py` from `analysis_panel.csv`
({len(panel)} district-months, {panel["district"].nunique()} districts,
{panel["year"].min()}–{panel["year"].max()}).*

## 1. Where cases concentrate

{_md_table(band_tbl, "band")}

Cases are not spread evenly across the elevation gradient — the
**{band_tbl["share_pct"].idxmax()}** belt carries the largest share
({band_tbl["share_pct"].max():g}%). Heaviest districts:

{", ".join(f"{d} ({int(c):,})" for d, c in top.items())}.

## 2. Seasonality

Peak month of mean cases — overall: **{peaks["All"]}**;
{"; ".join(f"{b}: {m}" for b, m in peaks.items() if b != "All")}.
The outbreak is a sharp Jul–Oct surge (see
`cases_climate_overlay.png` and `seasonality_by_band.png`).

## 3. Cases vs climate (Pearson r)

Overall correlation of monthly cases with each climate variable:

{_md_table(overall_corr.to_frame("r_overall"), "variable")}

By band (does the climate–cases link change with elevation?):

{_md_table(per_band_corr.T, "variable")}

The strongest single contemporaneous association is **{strongest}**
(r = {overall_corr[strongest]:g}). Same-month correlations are modest, which is
expected: climate is thought to *lead* cases by 1–2 months — quantified in the
lag analysis, not here.

## 4. Distribution & overdispersion

{_md_table(disp, "group")}

Monthly counts are **zero-heavy** ({zero:g}% of district-months are zero) and
**overdispersed**: the variance is {ratio:g}× the mean overall. This rules out
Poisson and motivates the **negative-binomial** model used downstream.

## 5. Implications for modeling

- Use a **negative-binomial** GLM (overdispersion above).
- Test **lagged** climate predictors (same-month r is weak; see the lag analysis).
- Keep an **elevation-band × climate** interaction: the per-band correlations
  above differ, hinting the climate response is not uniform across the gradient.
- No anomalies found that require new cleaning rules; the panel is complete
  (no nulls, expected row count) from the panel build.
"""
    out_path = get_path("reports") / "eda_findings.md"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(md, encoding="utf-8")
    return out_path


def main() -> None:
    panel = load_panel()
    fig_dir = get_path("figures")

    figures = {
        "cases_climate_overlay": plot_cases_climate_overlay,
        "seasonality_by_band": plot_seasonality_by_band,
        "correlation_heatmap": plot_correlation_heatmap,
        "cases_concentration": plot_cases_concentration,
        "cases_distribution": plot_cases_distribution,
    }
    for name, fn in figures.items():
        path = fn(panel, fig_dir / f"{name}.png")
        print(f"saved {path.relative_to(PROJECT_ROOT)}")

    disp = overdispersion(panel)
    overall_corr, per_band_corr = correlations(panel)
    band_tbl, top = concentration(panel)
    peaks = peak_months(panel)

    print("\n=== Overdispersion (cases) ===")
    print(disp.to_string())
    print("\n=== Cases vs climate (overall Pearson r) ===")
    print(overall_corr.to_string())
    print("\n=== Cases vs climate by band ===")
    print(per_band_corr.to_string())
    print("\n=== Cases by elevation band ===")
    print(band_tbl.to_string())
    print("\n=== Peak month of mean cases ===")
    print("; ".join(f"{b}: {m}" for b, m in peaks.items()))

    note = write_findings(
        panel, disp, overall_corr, per_band_corr, band_tbl, top, peaks
    )
    print(f"\nwrote {note.relative_to(PROJECT_ROOT)}")


if __name__ == "__main__":
    main()
